//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmbulanteSemiestacionario
    {
        public int IdAmbulanteSemiestacionario { get; set; }
        public Nullable<System.DateTime> FechaAmbulanteSemiestacionario { get; set; }
        public string FormaTrabajoAmbulanteAmbulanteSemiestacionario { get; set; }
        public string MunicipicioAmbulanteSemiestacionario { get; set; }
        public string AmbitoTerritorialAmbulanteSemiestacionario { get; set; }
        public string NombresAmbulanteSemiestacionario { get; set; }
        public string ApellidosAmbulanteSemiestacionario { get; set; }
        public string TipoIdentificacionAmbulanteSemiestacionario { get; set; }
        public Nullable<long> NumeroIDAmbulanteSemiestacionario { get; set; }
        public Nullable<System.DateTime> FechaNacimientoAmbulanteSemiestacionario { get; set; }
        public string OficioAmbulanteSemiestacionario { get; set; }
        public string SexoAmbulanteSemiestacionario { get; set; }
        public string EducacionAmbulanteSemiestacionario { get; set; }
        public string PoblacionAmbulanteSemiestacionario { get; set; }
        public string CondicionAmbulanteSemiestacionario { get; set; }
        public string OrgnizacionSocialAmbulanteSemiestacionario { get; set; }
        public string SeguridadSocialAmbulanteSemiestacionario { get; set; }
        public string AntiguedadTrabajoAmbulanteSemiestacionario { get; set; }
        public string JornadaAmbulanteSemiestacionario { get; set; }
        public string HorasDiasAmbulanteSemiestacionario { get; set; }
        public string DiasSemanaAmbulanteSemiestacionario { get; set; }
        public string DesplazamientoAmbulanteSemiestacionario { get; set; }
        public string EnfermedadAmbulanteSemiestacionario { get; set; }
        public string SustaniaAmbulanteSemiestacionario { get; set; }
        public string AlcoholAmbulanteSemiestacionario { get; set; }
        public string ActividadFisicaAmbulanteSemiestacionario { get; set; }
        public string HorasDuermeAmbulanteSemiestacionario { get; set; }
        public string FrutasVerdurasAmbulanteSemiestacionario { get; set; }
        public string ComportamientoAmbulanteSemiestacionario { get; set; }
        public string SintomasAmbulanteSemiestacionario { get; set; }
        public string AcidenteAmbulanteSemiestacionario { get; set; }
        public string DiscapacidadAmbulanteSemiestacionario { get; set; }
        public string SeguridadAmbulanteSemiestacionario { get; set; }
        public string PeligroFisicoAmbulanteSemiestacionario { get; set; }
        public string PeligroBiomecanicoAmbulanteSemiestacionario { get; set; }
        public string PeligroQuimicoAmbulanteSemiestacionario { get; set; }
        public string PeligroBiologicoAmbulanteSemiestacionario { get; set; }
        public string PeligroPsicosocialAmbulanteSemiestacionario { get; set; }
        public string AguaAmbulanteSemiestacionario { get; set; }
        public string ExcretaAmbulanteSemiestacionario { get; set; }
        public string ResiduosAmbulanteSemiestacionario { get; set; }
        public string CombustibleAmbulanteSemiestacionario { get; set; }
    }
}
