//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CondicionesSalud
    {
        public int IdCondicionesSalud { get; set; }
        public string EstadoSalud { get; set; }
        public string SaludFisica { get; set; }
        public string SaludMental { get; set; }
        public string SaludPsicologica { get; set; }
        public string ActividadNormalFisica { get; set; }
        public string CausaActividadFisica { get; set; }
        public string AccidenteLaborar { get; set; }
        public string AccidenteOrigen { get; set; }
        public string AccidneteTrabajoActividad { get; set; }
        public string EnfermedadOrigen { get; set; }
        public string EnfermedadOrigenOcupacional { get; set; }
        public string LesionesOcurridad { get; set; }
        public string ParteCuerpoLesion { get; set; }
        public string AgenteAccidente { get; set; }
        public string MecanismoAccidente { get; set; }
        public string InformoAccidente { get; set; }
        public string NoInformoAccidente { get; set; }
        public string ActorInformoAccidente { get; set; }
        public string IncapacidadAccidente { get; set; }
        public string CostosAccidente { get; set; }
        public string TramiteEnfermedad { get; set; }
        public string EnfermedadDiagnosticada { get; set; }
        public string CausaDiscapacidad { get; set; }
        public string TipoDiscapacidad { get; set; }
        public Nullable<int> IdSitic { get; set; }
    
        public virtual SiTic SiTic { get; set; }
    }
}
