//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CondicionesTrabajo
    {
        public int IdCondicionesTrabajo { get; set; }
        public string CondicionTrabajo { get; set; }
        public string PeligrosFisico { get; set; }
        public string PeligrosPsicosocial { get; set; }
        public string Peligrosbiologico { get; set; }
        public string CondicionesSeguridad { get; set; }
        public string PeligrosBiomecanicos { get; set; }
        public string PeligrosQuimicos { get; set; }
        public string FenomenosNatural { get; set; }
        public string ElementosProteccion { get; set; }
        public string ProteccionCabeza { get; set; }
        public string ProteccionOcular { get; set; }
        public string ProteccionAuditiva { get; set; }
        public string ProteccionRespiratoria { get; set; }
        public string ExtremidadesSuperiores { get; set; }
        public string ExtremidadesInferiores { get; set; }
        public string OtrosElementos { get; set; }
        public string RopaTrabajo { get; set; }
        public string EmergenciaEncuestado { get; set; }
        public string CasoEmergencia { get; set; }
        public string Extintores { get; set; }
        public string Botiquin { get; set; }
        public string RutaEvacuacion { get; set; }
        public string SalidaEmergencia { get; set; }
        public string LugarCasoEmergencia { get; set; }
        public string AguaPotable { get; set; }
        public string RecoleccionResiduos { get; set; }
        public Nullable<System.TimeSpan> HoraTerminacion { get; set; }
        public string NombreEncuestado { get; set; }
        public Nullable<long> CedulaEncuestado { get; set; }
        public string Firma { get; set; }
        public Nullable<int> IdSitic { get; set; }
    
        public virtual SiTic SiTic { get; set; } = new SiTic();
    }
}
