//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estacionario
    {
        public int IdEstacionario { get; set; }
        public Nullable<System.DateTime> FechaEstacionario { get; set; }
        public string TrabajadorEstacionario { get; set; }
        public string MunicipioEstacionario { get; set; }
        public string TerritorioEstacionario { get; set; }
        public string NombresEstacionario { get; set; }
        public string ApellidosEstacionario { get; set; }
        public string TipoIdentificacionEstacionario { get; set; }
        public Nullable<long> NumeroIdentificacionEstacionario { get; set; }
        public Nullable<System.DateTime> FechaNacimientoEstacionario { get; set; }
        public string OcupacionEstacionario { get; set; }
        public string LugarTrabajoEstacionario { get; set; }
        public string PersonaContactoEstacionario { get; set; }
        public string TelefonoEstacionario { get; set; }
        public string DireccionTrabajoEstacionario { get; set; }
        public string ActividadEconomicaEstacionario { get; set; }
        public string AguaConsumoEstacionario { get; set; }
        public string TratamientoAguaEstacionario { get; set; }
        public string AlmacenamientoAguaEstacionario { get; set; }
        public string ExcretaEstacionario { get; set; }
        public string ResiduosEstacionario { get; set; }
        public string ResiduosSolidosEstacionario { get; set; }
        public string AguasResidualesEstacionario { get; set; }
        public string CombustibleEstacionario { get; set; }
        public string UsoQuimicosEstacionario { get; set; }
        public string AlmacenanQuimicosEstacionario { get; set; }
        public string GeneranResiduosPeligrososEstacionario { get; set; }
        public string DisponenResiduosPeligrososEstacionario { get; set; }
        public string PlagasEstacionario { get; set; }
        public string AnimalesVenenososEstacionario { get; set; }
        public string RiesgosAnimalesVenenososEstacionario { get; set; }
    }
}
