//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstiloVida
    {
        public int IdEstiloVida { get; set; }
        public string Peso { get; set; }
        public string Estatura { get; set; }
        public string ActividadFisica { get; set; }
        public string DiasSemana { get; set; }
        public string HorasPractica { get; set; }
        public string EncuestadoFuma { get; set; }
        public string ConsumeLicor { get; set; }
        public string SustanciasPsicoactivas { get; set; }
        public string CualSustancia { get; set; }
        public string DietaFrutas { get; set; }
        public string FrecuenciaFrutas { get; set; }
        public Nullable<int> IdSitic { get; set; }
    
        public virtual SiTic SiTic { get; set; } = new SiTic();
    }
}
