//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeAccidenteTrabajo
    {
        public int IdAccidenteTrabajo { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string TipoIdentificacion { get; set; }
        public Nullable<long> NumeroIdentificacion { get; set; }
        public Nullable<System.DateTime> FechaNacimimiento { get; set; }
        public string Sexo { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Departamento { get; set; }
        public string Municipio { get; set; }
        public string Zona { get; set; }
        public string Ocupacion { get; set; }
        public string TipoAfiliacion { get; set; }
        public string Tipocontributivo { get; set; }
        public string Sisben { get; set; }
        public string FondoPensiones { get; set; }
        public string EpsAfiliado { get; set; }
        public string InstitucionPrestadoraSalud { get; set; }
        public string SectorEconomico { get; set; }
        public string ActividadEconomica { get; set; }
        public string TipoVenta { get; set; }
        public string DireccionEconomica { get; set; }
        public string TelefonoEconomica { get; set; }
        public string ZonaEconomica { get; set; }
        public string DescripcionAccidente { get; set; }
        public string PresenciaronAccidente { get; set; }
        public string ApellidosNombresAccidente { get; set; }
        public string DocumentoIdentidadAccidente { get; set; }
        public Nullable<long> NumeroDocumentoAccidente { get; set; }
        public string OcupacionAccidente { get; set; }
        public string NombresApellidosResponsable { get; set; }
        public string TipoDocumentoResponsable { get; set; }
        public Nullable<long> NumeroDocumentoResponsable { get; set; }
        public string FirmaResponsable { get; set; }
        public Nullable<System.DateTime> FechaResponsable { get; set; }
    }
}
