//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Permisos()
        {
            this.ASignarPermisos = new HashSet<ASignarPermisos>();
        }
    
        public int IdPermiso { get; set; }
        public Nullable<int> CodPermiso { get; set; }
        public string NomPermiso { get; set; }
        public string EtiquetaPermiso { get; set; }
        public string Url { get; set; }
        public string DesPermiso { get; set; }
        public Nullable<int> TipoPermiso { get; set; }
        public string PadrePermiso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASignarPermisos> ASignarPermisos { get; set; }
        public virtual TipoPermiso TipoPermiso1 { get; set; }
    }
}
