//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguridadSocial
    {
        public int IdSeguridadSocial { get; set; }
        public string AfiliadoSeguridad { get; set; }
        public string RegimenAfiliado { get; set; }
        public string RegimenSalud { get; set; }
        public string EpsAfiliado { get; set; }
        public string Pensiones { get; set; }
        public string Afp { get; set; }
        public Nullable<int> IdSitic { get; set; }
    
        public virtual SiTic SiTic { get; set; } = new SiTic();
    }
}
