//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiTic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SiTic()
        {
            this.SeguridadSocial = new HashSet<SeguridadSocial>();
            this.EstiloVida = new HashSet<EstiloVida>();
            this.CondicionesSalud = new HashSet<CondicionesSalud>();
            this.CondicionesTrabajo = new HashSet<CondicionesTrabajo>();
            this.SocioDemograficos = new HashSet<SocioDemograficos>();
            this.SocioEconomicos = new HashSet<SocioEconomicos>();
        }
    
        public int IdSitic { get; set; }
        public string AfiliacionActualEncuestado { get; set; }
        public Nullable<System.DateTime> FechaEncuesta { get; set; }
        public Nullable<System.TimeSpan> HoraInicioEncuesta { get; set; }
        public string TipoDocumentoEncuestador { get; set; }
        public Nullable<long> NumeroIdentificacionEncuestador { get; set; }
        public string TrabajadoInformal { get; set; }
        public string DepartamentoEncuestador { get; set; }
        public string MunicipioEncuestador { get; set; }
        public string ClaseMunicipioEncuestador { get; set; }
        public string TipoDocumentoEncuestado { get; set; }
        public Nullable<long> NumeroIdentificacionEncuestado { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Direccion { get; set; }
        public string UsuarioRegistro { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeguridadSocial> SeguridadSocial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstiloVida> EstiloVida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CondicionesSalud> CondicionesSalud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CondicionesTrabajo> CondicionesTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocioDemograficos> SocioDemograficos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocioEconomicos> SocioEconomicos { get; set; } 
    }
}
