//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocioDemograficos
    {
        public int IdSocioDemograficos { get; set; }
        public string Genero { get; set; }
        public string EstadoCivil { get; set; }
        public string NivelEscolar { get; set; }
        public string OtroNivelEscolar { get; set; }
        public Nullable<int> AñosAprobados { get; set; }
        public string CabezaFamilia { get; set; }
        public string EconomiaFamilia { get; set; }
        public Nullable<int> DependenciaFamiliar { get; set; }
        public Nullable<int> DependenciaMenores { get; set; }
        public string TipoPoblacion { get; set; }
        public string CondicionesTrabajo { get; set; }
        public string OcupacionActual { get; set; }
        public string MotivoDesplazamiento { get; set; }
        public Nullable<int> IdSitic { get; set; }
    
        public virtual SiTic SiTic { get; set; }= new SiTic();
    }
}
